org: hammady
app: wwpray
service: subscriber
frameworkVersion: '3'

params:
  default:
    contact_list_name: ${file(../common-params.yml):contact_list_name}
    email_template: wwpray-subscription-confirmation-${sls:stage}
    email_from: ${file(../common-params.yml):email_from}
    feedback_email: ${file(../common-params.yml):feedback_email_user}@${file(../common-params.yml):${sls:stage}.custom_domain}
    website_url: https://${file(../common-params.yml):${sls:stage}.custom_domain}
  dev:
    log_level: debug
  prod:
    log_level: info

provider:
  name: aws
  runtime: python3.9
  environment:
    LOG_LEVEL: ${param:log_level}
    CONTACT_LIST_NAME: ${param:contact_list_name}
    EMAIL_FROM: ${param:email_from}
    EMAIL_TEMPLATE: ${param:email_template}
  httpApi:
    cors: true
  logs:
    httpApi: true
  iam:
    role:
      statements:
        # Allow functions to manage contacts and send emails
        - Effect: Allow
          Action:
            - 'ses:GetContactList'
            - 'ses:GetContact'
            - 'ses:UpdateContact'
            - 'ses:CreateContact'
            - 'ses:SendTemplatedEmail'
          Resource: '*'

functions:
  subscriptionHandler:
    handler: handler.run
    events:
      - httpApi:
          path: /
          # support any method
          method: '*'


plugins:
  - serverless-python-requirements

resources:
  Resources:
    SESTemplate:
      Type: AWS::SES::Template
      Properties:
        Template:
          TemplateName: ${param:email_template}
          SubjectPart: "Subscription confirmation"
          TextPart: ''
          HtmlPart: |
            Dear subscriber,<br/>
            This is to confirm that you have subscribed to notifications of prayer time updates for the following:<br/>
            <ol>
                {{#each topics}}
                <li>{{.}} Masjid</li>
                {{/each}}
            </ol>

            <p>
            To manage your subscriptions, please <a href="{{amazonSESUnsubscribeUrl}}">click here</a>.
            </p>

            <p>
            Regards,<br/>
            The WWPray team<br/>
            ${param:website_url}<br/>
            For feedback, please email <a href="mailto:${param:feedback_email}">${param:feedback_email}</a><br/>
            Proudly open-sourced on <a href="https://github.com/hammady/wwpray">Github</a><br/>
            </p>
