org: hammady
app: wwpray
service: subscriber
frameworkVersion: '3'

params:
  dev:
    log_level: debug
    feedback_email: hello@dev.wwpray.net
    email_template: wwpray-subscription-confirmation-dev
    website_url: http://dev.wwpray.net
  prod:
    log_level: info
    feedback_email: hello@wwpray.net
    email_template: wwpray-subscription-confirmation-prod
    website_url: https://wwpray.net

provider:
  name: aws
  runtime: python3.9
  environment:
    LOG_LEVEL: ${param:log_level}
    CONTACT_LIST_NAME: wwpray
    EMAIL_FROM: WWPray Notifications <noreply@wwpray.net>
    EMAIL_TEMPLATE: ${param:email_template}
  httpApi:
    cors: true
  logs:
    httpApi: true
  iam:
    role:
      statements:
        # Allow functions to manage contacts and send emails
        - Effect: Allow
          Action:
            - 'ses:GetContactList'
            - 'ses:GetContact'
            - 'ses:UpdateContact'
            - 'ses:CreateContact'
            - 'ses:SendTemplatedEmail'
          Resource: '*'

functions:
  subscriptionHandler:
    handler: handler.run
    events:
      - httpApi:
          path: /
          # support any method
          method: '*'


plugins:
  - serverless-python-requirements

resources:
  Resources:
    SESTemplate:
      Type: AWS::SES::Template
      Properties:
        Template:
          TemplateName: ${param:email_template}
          SubjectPart: "Subscription confirmation"
          TextPart: ''
          HtmlPart: |
            Dear subscriber,<br/>
            This is to confirm that you have subscribed to notifications of prayer time updates for the following:<br/>
            <ol>
                {{#each topics}}
                <li>{{.}} Masjid</li>
                {{/each}}
            </ol>

            <p>
            To manage your subscriptions, please <a href="{{amazonSESUnsubscribeUrl}}">click here</a>.
            </p>

            <p>
            Regards,<br/>
            The WWPray team<br/>
            ${param:website_url}<br/>
            For feedback, please email <a href="mailto:${param:feedback_email}">${param:feedback_email}</a><br/>
            <a href="https://github.com/hammady/wwpray">Github</a><br/>
            </p>
