org: hammady
app: wwpray
service: scraper

frameworkVersion: '3'

params:
  dev:
    log_level: debug
    s3_bucket: wwpray-dev
    cron_enabled: false
  prod:
    log_level: info
    s3_bucket: wwpray-prod
    cron_enabled: true

provider:
  name: aws
  runtime: python3.9	
  environment:
    LOG_LEVEL: ${param:log_level}
    S3_BUCKET: ${param:s3_bucket}
  iam:
    role:
      statements:
        # Allow functions to write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::${param:s3_bucket}/*'

functions:
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every 6 hours on minute 0
      - schedule:
          rate: cron(0 */6 * * ? *)
          enabled: ${param:cron_enabled}
resources:
  Resources:
    S3Bucketwwpray:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${param:s3_bucket}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - HEAD
              MaxAge: 3000

plugins:
  - serverless-python-requirements
