service: scraper

frameworkVersion: '3'

params:
  default:
    sources: MNNexusSource,ShalimarSource,ICCOSource,WEICSource,ISNACanadaSource,DarFoundationSource,AlfalahSource,AlfarooqSource,ArRehmanSource,MICSource,DarulTaqwaSource
    s3_bucket: ${file(../common-params.yml):data_bucket_prefix}-${sls:stage}
    admin_email: ${env:ADMIN_EMAIL}
  dev:
    log_level: debug
    cron_enabled: false
  prod:
    log_level: info
    cron_enabled: true

provider:
  name: aws
  runtime: python3.9
  environment:
    LOG_LEVEL: ${param:log_level}
    S3_BUCKET: ${param:s3_bucket}
    SOURCES: ${param:sources}
  iam:
    role:
      statements:
        # Allow functions to write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::${param:s3_bucket}/data/*'

functions:
  cronHandler:
    handler: handler.run
    timeout: 30 # default is 6, TODO optimize later by doing requests in parallel
    maximumRetryAttempts: 0 # don't retry on failure, since we will run again in a few hours
    events:
      # Invoke Lambda function everyday at 7am UTC
      - schedule:
          rate: cron(0 3,7,15,22 * * ? *)
          enabled: ${param:cron_enabled}
      # Invoke Lambda function more frequently on Fridays
      - schedule:
          rate: cron(0 14,16 ? * FRI *)
          enabled: ${param:cron_enabled}

plugins:
  - serverless-python-requirements

resources:
  Resources:
    ScraperErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: scraper-lambda-errors-${sls:stage}
        AlarmDescription: "WWPray Scraper Lambda function failed"
        Namespace: AWS/Lambda
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !Ref CronHandlerLambdaFunction
        Statistic: Sum
        Period: 300
        EvaluationPeriods: 1
        Threshold: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        TreatMissingData: notBreaching
        AlarmActions:
          - !Ref AlertTopic

    AlertTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: scraper-alerts-${sls:stage}
        Subscription:
          - Protocol: email
            Endpoint: ${param:admin_email}
