org: hammady
app: wwpray
service: scraper

frameworkVersion: '3'

params:
  default:
    sources: MNNexusSource,ShalimarSource,ICCOSource,WEICSource,ISNACanadaSource,DarFoundationSource,AlfalahSource,AlfarooqSource
  dev:
    log_level: debug
    s3_bucket: wwpray-dev
    cron_enabled: false
  prod:
    log_level: info
    s3_bucket: wwpray-prod
    cron_enabled: true

provider:
  name: aws
  runtime: python3.9
  environment:
    LOG_LEVEL: ${param:log_level}
    S3_BUCKET: ${param:s3_bucket}
    SOURCES: ${param:sources}
  iam:
    role:
      statements:
        # Allow functions to write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::${param:s3_bucket}/data/*'

functions:
  cronHandler:
    handler: handler.run
    timeout: 20 # default is 6, TODO optimize later by doing requests in parallel
    events:
      # Invoke Lambda function everyday at 7am UTC
      - schedule:
          rate: cron(0 7 * * ? *)
          enabled: ${param:cron_enabled}

plugins:
  - serverless-python-requirements
