org: hammady
app: wwpray
service: notifier

frameworkVersion: '3'

params:
  dev:
    log_level: debug
    s3_bucket: wwpray-dev
    event_enabled: false
  prod:
    log_level: info
    s3_bucket: wwpray-prod
    event_enabled: true

provider:
  name: aws
  runtime: python3.9	
  environment:
    LOG_LEVEL: ${param:log_level}
    S3_BUCKET: ${param:s3_bucket}
    CONTACT_LIST_NAME: wwpray
    EMAIL_FROM: wwpray-noreply@hammady.net
    EMAIL_TEMPLATE: wwpray-iqamas-changed
  iam:
    role:
      statements:
        # Allow functions to write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:DeleteObject'
          Resource:
            - 'arn:aws:s3:::${param:s3_bucket}/*'
        # Allow functions to manage contact lists and send emails
        - Effect: Allow
          Action:
            - 'ses:GetContactList'
            - 'ses:UpdateContactList'
            - 'ses:CreateContactList'
            - 'ses:ListContacts'
            - 'ses:SendTemplatedEmail'
          Resource: '*'

functions:
  s3fileHandler:
    handler: handler.run
    events:
      # Invoke Lambda function each time a new object is created in the bucket
      - s3:
          bucket: ${param:s3_bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: data/
            - suffix: scraped.json
          existing: true
          forceDeploy: true # to force deploy the s3 trigger on an existing bucket

plugins:
  - serverless-python-requirements
