org: hammady
app: wwpray
service: notifier

frameworkVersion: '3'

params:
  default:
    contact_list_name: ${file(../common-params.yml):contact_list_name}
    s3_bucket: ${file(../common-params.yml):data_bucket_prefix}-${sls:stage}
    email_template: wwpray-times-changed-${sls:stage}
    email_from: ${file(../common-params.yml):email_from}
    feedback_email: ${file(../common-params.yml):feedback_email_user}@${file(../common-params.yml):${sls:stage}.custom_domain}
    website_url: https://${file(../common-params.yml):${sls:stage}.custom_domain}
  dev:
    log_level: debug
    event_enabled: false
    send_all_to: MUST_BE_NON_EMPTY_IN_DEV
  prod:
    log_level: info
    event_enabled: true
    send_all_to: ""

provider:
  name: aws
  runtime: python3.9
  environment:
    LOG_LEVEL: ${param:log_level}
    S3_BUCKET: ${param:s3_bucket}
    CONTACT_LIST_NAME: ${param:contact_list_name}
    EMAIL_FROM: ${param:email_from}
    EMAIL_TEMPLATE: ${param:email_template}
    SEND_ALL_TO: ${param:send_all_to}
  iam:
    role:
      statements:
        # Allow functions to write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:DeleteObject'
          Resource:
            - 'arn:aws:s3:::${param:s3_bucket}/data/*'
        # Allow functions to manage contact lists and send emails
        - Effect: Allow
          Action:
            - 'ses:GetContactList'
            - 'ses:UpdateContactList'
            - 'ses:CreateContactList'
            - 'ses:ListContacts'
            - 'ses:SendTemplatedEmail'
          Resource: '*'

functions:
  s3fileHandler:
    handler: handler.run
    timeout: 15 # default is 6, TODO optimize later by doing requests in parallel
    events:
      # Invoke Lambda function each time a new object is created in the bucket
      - s3:
          bucket: ${param:s3_bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: data/
            - suffix: scraped.json
          existing: true
          forceDeploy: true # to force deploy the s3 trigger on an existing bucket

plugins:
  - serverless-python-requirements

resources:
  Resources:
    SESTemplate:
      Type: AWS::SES::Template
      Properties:
        Template:
          TemplateName: ${param:email_template}
          SubjectPart: "{{masjid_name}} prayer times changed"
          TextPart: ''
          HtmlPart: |
            Dear subscriber,<br/>
            The prayer times have changed for the masjid you have subscribed to:
            <a href="{{masjid_url}}">{{masjid_name}}</a>.<br/>
            <i>Address: {{masjid_address}}</i>.<br/><br/>
            Below are the new iqama times:<br/>
            <ol>
                <li>Fajr: {{iqamas.fajr.time}} {{#if iqamas.fajr.changed }} <strong>(Changed)</strong> {{/if}} </li>
                <li>Zuhr: {{iqamas.zuhr.time}} {{#if iqamas.zuhr.changed }} <strong>(Changed)</strong> {{/if}} </li>
                <li>Asr: {{iqamas.asr.time}} {{#if iqamas.asr.changed }} <strong>(Changed)</strong> {{/if}} </li>
                <li>Maghrib: {{iqamas.maghrib.time}} {{#if iqamas.maghrib.changed }} <strong>(Changed)</strong> {{/if}} </li>
                <li>Isha: {{iqamas.isha.time}} {{#if iqamas.isha.changed }} <strong>(Changed)</strong> {{/if}} </li>
            </ol>

            Jumuaa times: {{#if jumas_changed }} <strong>(Changed)</strong> {{/if}} <br/>
            <ol>
                {{#each jumas}}
                <li>{{.}}</li>
                {{/each}}
            </ol>

            <p>
            To stop receiving these emails, or to subscribe to more masjids, please <a href="{{amazonSESUnsubscribeUrl}}">click here</a>.
            </p>

            <p>
            Regards,<br/>
            The WWPray team<br/>
            ${param:website_url}<br/>
            For feedback, please email <a href="mailto:${param:feedback_email}">${param:feedback_email}</a><br/>
            Proudly open-sourced on <a href="https://github.com/hammady/wwpray">Github</a><br/>
            </p>
