# github action to deploy scraper sls service to prod

name: Test (always) and deploy (on push) scraper service

on:
  push:
    branches:
      - main
    paths: &scraper_paths
      - scraper/**
      - .github/workflows/sls-scraper.yaml
  pull_request:
    paths: *scraper_paths

jobs:
  test-and-deploy:
    name: Test and (if push) deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install serverless framework
        run: npm install -g serverless@3.38.0
      - name: Install node dependencies
        working-directory: scraper
        run: npm ci
      - name: Run tests
        working-directory: scraper
        run: npm run test
      - name: Install python3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Package and deploy
        if: github.event_name == 'push'
        working-directory: scraper
        run: |
          serverless deploy \
            --region ${{ vars.AWS_REGION }} \
            --stage ${{ vars.SLSSTAGE }} \
            --verbose
